from functools import lru_cache

from ._core import (
    decode_entity_styles,
    decode_layer_colors,
    decode_layer_names,
    decode_arc_entities,
    decode_line_arc_circle_entities,
    decode_3dface_entities,
    decode_attrib_entities,
    decode_attdef_entities,
    decode_circle_entities,
    decode_ellipse_entities,
    decode_spline_entities,
    decode_dimension_entities,
    decode_dim_diameter_entities,
    decode_dim_ordinate_entities,
    decode_dim_aligned_entities,
    decode_dim_ang3pt_entities,
    decode_dim_ang2ln_entities,
    decode_dim_linear_entities,
    decode_dim_radius_entities,
    decode_insert_entities,
    decode_insert_minsert_entities,
    decode_insert_minsert_dimension_entities,
    decode_block_header_names,
    decode_block_entity_names,
    decode_block_entity_name_maps,
    decode_line_entities,
    decode_lwpolyline_entities,
    decode_minsert_entities,
    decode_mtext_entities,
    decode_leader_entities,
    decode_hatch_entities,
    decode_tolerance_entities,
    decode_mline_entities,
    decode_point_entities,
    decode_polyline_3d_entities,
    decode_polyline_3d_with_vertices,
    decode_polyline_mesh_entities,
    decode_polyline_mesh_with_vertices,
    decode_polyline_pface_entities,
    decode_polyline_pface_with_faces,
    decode_solid_entities,
    decode_trace_entities,
    decode_shape_entities,
    decode_viewport_entities,
    decode_oleframe_entities,
    decode_ole2frame_entities,
    decode_long_transaction_entities,
    decode_region_entities,
    decode_3dsolid_entities,
    decode_body_entities,
    decode_ray_entities,
    decode_xline_entities,
    decode_polyline_2d_entities,
    decode_polyline_2d_entities_interpreted,
    decode_polyline_2d_with_vertex_data,
    decode_polyline_sequence_members,
    decode_polyline_2d_with_vertices,
    decode_polyline_2d_with_vertices_interpolated,
    decode_text_entities,
    decode_vertex_3d_entities,
    decode_vertex_mesh_entities,
    decode_vertex_pface_entities,
    decode_vertex_pface_face_entities,
    decode_vertex_2d_entities,
    detect_version,
    write_ac1015_dwg,
    write_ac1015_line_dwg,
    list_object_headers,
    list_object_headers_by_type,
    list_object_headers_with_type,
    list_object_map_entries,
    list_section_locators,
    decode_object_entity_layer_handles,
    read_object_records_by_handle,
    read_object_records_by_offset,
    read_object_records_by_type,
    read_section_bytes,
    decode_object_handle_stream_refs,
    decode_acis_candidate_infos,
    decode_proxy_graphic_chunk_infos,
    decode_proxy_graphic_text_entities,
)
from ._embedded_text import collect_unknown_embedded_text_entities

__all__ = [
    "detect_version",
    "list_section_locators",
    "read_section_bytes",
    "list_object_map_entries",
    "list_object_headers",
    "list_object_headers_by_type",
    "list_object_headers_with_type",
    "read_object_records_by_handle",
    "read_object_records_by_offset",
    "read_object_records_by_type",
    "decode_object_entity_layer_handles",
    "decode_object_handle_stream_refs",
    "decode_acis_candidate_infos",
    "decode_unknown_embedded_text_entities",
    "decode_proxy_graphic_chunk_infos",
    "decode_proxy_graphic_text_entities",
    "decode_entity_styles",
    "decode_layer_colors",
    "decode_layer_names",
    "decode_line_entities",
    "decode_point_entities",
    "decode_3dface_entities",
    "decode_arc_entities",
    "decode_line_arc_circle_entities",
    "decode_attrib_entities",
    "decode_attdef_entities",
    "decode_circle_entities",
    "decode_ellipse_entities",
    "decode_spline_entities",
    "decode_dimension_entities",
    "decode_dim_diameter_entities",
    "decode_dim_ordinate_entities",
    "decode_dim_aligned_entities",
    "decode_dim_ang3pt_entities",
    "decode_dim_ang2ln_entities",
    "decode_dim_linear_entities",
    "decode_dim_radius_entities",
    "decode_text_entities",
    "decode_mtext_entities",
    "decode_leader_entities",
    "decode_hatch_entities",
    "decode_tolerance_entities",
    "decode_mline_entities",
    "decode_insert_entities",
    "decode_insert_minsert_entities",
    "decode_insert_minsert_dimension_entities",
    "decode_block_header_names",
    "decode_block_entity_names",
    "decode_block_entity_name_maps",
    "decode_minsert_entities",
    "decode_lwpolyline_entities",
    "decode_polyline_3d_entities",
    "decode_polyline_3d_with_vertices",
    "decode_polyline_mesh_entities",
    "decode_polyline_mesh_with_vertices",
    "decode_polyline_pface_entities",
    "decode_polyline_pface_with_faces",
    "decode_solid_entities",
    "decode_trace_entities",
    "decode_shape_entities",
    "decode_viewport_entities",
    "decode_oleframe_entities",
    "decode_ole2frame_entities",
    "decode_long_transaction_entities",
    "decode_region_entities",
    "decode_3dsolid_entities",
    "decode_body_entities",
    "decode_ray_entities",
    "decode_xline_entities",
    "decode_polyline_2d_entities",
    "decode_polyline_2d_entities_interpreted",
    "decode_polyline_2d_with_vertices",
    "decode_polyline_2d_with_vertices_interpolated",
    "decode_polyline_2d_with_vertex_data",
    "decode_polyline_sequence_members",
    "decode_vertex_3d_entities",
    "decode_vertex_mesh_entities",
    "decode_vertex_pface_entities",
    "decode_vertex_pface_face_entities",
    "decode_vertex_2d_entities",
    "write_ac1015_dwg",
    "write_ac1015_line_dwg",
]


@lru_cache(maxsize=16)
def _decode_unknown_embedded_text_entities_cached(
    path: str,
    modelspace_owner_handle: int | None,
    limit: int | None,
) -> tuple[tuple[int, str, tuple[float, float, float], float, float, int | None], ...]:
    return collect_unknown_embedded_text_entities(
        path,
        list_object_headers_with_type,
        read_object_records_by_handle,
        modelspace_owner_handle=modelspace_owner_handle,
        limit=limit,
    )


def decode_unknown_embedded_text_entities(
    path: str,
    modelspace_owner_handle: int | None = None,
    limit: int | None = None,
) -> list[tuple[int, str, tuple[float, float, float], float, float, int | None]]:
    return list(
        _decode_unknown_embedded_text_entities_cached(
            str(path),
            None if modelspace_owner_handle is None else int(modelspace_owner_handle),
            None if limit is None else int(limit),
        )
    )
